# Site settings
title: eHealth Bootstrap Theme
email: brennan.novak@ehealthnigeria.org

description: A Jekyll config that renders a site for eHealth Bootstrap testing

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ehealthafrica.org" # the base hostname & protocol for your site

# Server
destination:      _gh_pages
encoding:         UTF-8

exclude:          ["bower_components", "node_modules", "grunt", "sass"]

# Custom vars
current_version:  3.3.1
repo:             https://github.com/eHealthAfrica/ehealth-bootstrap

twitter_username: ehealthafrica
github_username:  ehealthafrica

ehealth_versions: ["default"]
ehealth_theme_version: "default"
ehealth_apps:     ["call-center", "sense", "journal", "dashboard"]

# Build settings
markdown: kramdown